DOMとEOL
ohyama4z/Kakomon-Management-System pull request #93
Opened 2020-09-08 10:27 UTC by asann3

2020-09-08 12:15 UTC, satackey requested changes

2020-09-08 12:15 UTC, satackey commented on client/src/store/actions.ts
> +  const convertedCsvFile = hoge.join('\n') // csvHeaders + unionCsv + '\n'
`hoge` 🤔

2020-09-08 12:15 UTC, satackey commented on client/src/store/actions.ts
> +  console.log('contents', contents)
:eyes:

2020-09-08 12:15 UTC, satackey commented on client/src/store/actions.ts
> -  const convertedCsvFile = csvHeaders + unionCsv
`〇〇Csv` / `csv〇〇` 統一しましょう

2020-09-08 12:15 UTC, satackey commented on client/src/store/actions.ts
> +    console.log('content', content)
:eyes:

2020-09-08 12:15 UTC, satackey commented on client/src/store/actions.ts
> +const os = require('os')
これブラウザで動かない気がします

2020-09-08 12:15 UTC, satackey commented on client/src/store/actions.ts
> +      '\ufeff' + convertObjToCsv(Object.values(editedCsvObj)) + os.EOL // objArray
編集するOSによって毎回CSVファイルの改行コードが変わると困ります…現状に合わせて欲しいです！

2020-09-08 12:15 UTC, satackey commented on client/package.json
> +    "os": "^0.1.1",
https://github.com/DiegoRBaquero/node-os#this-is-a-nodejs-core-module
> #### This is a NodeJS Core Module
> **DO NOT INSTALL**

と書いてあるようです

2020-09-08 12:15 UTC, satackey commented on client/src/store/actions.ts
>      // const objArray = Object.values(editedCsvObj) as Array
これは残す必要がなさそうに思いました

2020-09-08 12:22 UTC, satackey reviewed
今回編集した部分の動作を確認できるように、`postCommitCsv` のチェック項目を追加して欲しいです。
https://github.com/ohyama4z/Kakomon-Management-System/blob/c7117a6604ce9036abb1395521b078b82ddfb14e/client/src/store/__tests__/actions.test.js#L840-L848

2020-09-08 12:45 UTC, satackey commented on client/src/store/actions.ts
> +  hoge.push(unionCsv)
```suggestion
  const hoge = [csvHeaders, unionCsv]
```

2020-09-08 15:00 UTC, asann3 commented
> 今回編集した部分の動作を確認できるように、`postCommitCsv` のチェック項目を追加して欲しいです。
> https://github.com/ohyama4z/Kakomon-Management-System/blob/c7117a6604ce9036abb1395521b078b82ddfb14e/client/src/store/__tests__/actions.test.js#L840-L848

https://github.com/ohyama4z/Kakomon-Management-System/blob/a76f58d9d48d4af990550b195941b03185e8adea/client/src/store/__tests__/actions.test.js#L421-L453

これではまずいですか？

2020-09-09 00:49 UTC, satackey requested changes
@asann3 なるほど。それであれば「今回編集した部分の動作」ではなかったですね

「`postCommitCsv` が `objectToCsv` を正しく使えていること」を確認できるようにして欲しいです

2020-09-09 00:49 UTC, satackey commented on client/src/store/actions.ts
>    const unionCsv = contents.join(`\n`)
なんか実際見ると違和感があったので調べてみたら、"union" は 〇〇union といった形で使われている場合が多いようです。
https://ejje.weblio.jp/content/union
というか "union" は人や組織的な意味で使われている場合が多そうなのでそもそも別の単語を用いるべきかも…と思いました

headersも同様な気がします（_カンマ区切りファイルのヘッダー_ / _ヘッダーのカンマ区切りファイル_）

2020-09-09 23:30 UTC, satackey commented on client/src/store/actions.ts
>    const unionCsv = contents.join(`\n`)
"integration" もそんなに変わらないような……。まあいいか
https://ejje.weblio.jp/content/integration

2020-10-22 12:29 UTC, ohyama4z approved these changes

2020-10-22 12:29 UTC, merged